"""
Persistent cache of information obtained from the Tuya cloud.

Local keys are regenerated by Tuya whenever a device is reset or re-paired,
so caching them (along with the cloud credentials needed to refresh them)
allows devices to be re-discovered and repaired without user interaction.
"""

import logging
from typing import Any

from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store

from .const import CONF_LOCAL_KEY, DATA_CLOUD_CACHE, DOMAIN

_LOGGER = logging.getLogger(__name__)

STORAGE_KEY = f"{DOMAIN}.cloud"
STORAGE_VERSION = 1


class CloudCache:
    """Stores cloud credentials and device local keys between restarts."""

    def __init__(self, hass: HomeAssistant) -> None:
        self._store = Store(hass, STORAGE_VERSION, STORAGE_KEY, private=True)
        self._auth: dict[str, Any] | None = None
        self._devices: dict[str, dict[str, Any]] = {}

    async def async_load(self) -> None:
        """Load the cache from disk."""
        data = await self._store.async_load()
        if data:
            self._auth = data.get("auth")
            self._devices = data.get("devices") or {}

    async def _async_save(self) -> None:
        await self._store.async_save(
            {
                "auth": self._auth,
                "devices": self._devices,
            }
        )

    @property
    def auth(self) -> dict[str, Any] | None:
        """Cached cloud authentication, if any."""
        return self._auth

    async def async_set_auth(self, auth: dict[str, Any] | None) -> None:
        """Store (or clear) the cloud authentication."""
        self._auth = auth or None
        await self._async_save()

    async def async_update_devices(self, devices: dict[str, Any]) -> None:
        """Merge cloud device information into the cache.

        Devices are keyed by device id. Entries without a local key are
        skipped so that a partial cloud response cannot erase a known key.
        """
        changed = False
        for device in devices.values():
            device_id = device.get("id")
            local_key = device.get(CONF_LOCAL_KEY)
            if not device_id or not local_key:
                continue
            entry = {
                CONF_LOCAL_KEY: local_key,
                "name": device.get("name"),
                "product_id": device.get("product_id"),
                "product_name": device.get("product_name"),
                "node_id": device.get("node_id"),
                "uuid": device.get("uuid"),
            }
            if self._devices.get(device_id) != entry:
                self._devices[device_id] = entry
                changed = True

        if changed:
            await self._async_save()

    def get_device(self, device_id: str) -> dict[str, Any] | None:
        """Cached cloud information for a device."""
        return self._devices.get(device_id)

    def get_local_key(self, device_id: str) -> str | None:
        """The cached local key for a device, if known."""
        device = self._devices.get(device_id)
        return device.get(CONF_LOCAL_KEY) if device else None

    def all_local_keys(self) -> dict[str, str]:
        """Every known local key, keyed by device id.

        Used to work out which device is at an address when it can only be
        reached by connecting to it rather than by listening for it.
        """
        return {
            device_id: device[CONF_LOCAL_KEY]
            for device_id, device in self._devices.items()
            if device.get(CONF_LOCAL_KEY)
        }

    def get_subdevice_local_key(self, device_cid: str) -> str | None:
        """The cached local key for a device behind a gateway.

        Sub devices are identified in the config entry by their node_id or
        uuid rather than by the device id, which belongs to the gateway.
        """
        for device in self._devices.values():
            if device_cid in (device.get("node_id"), device.get("uuid")):
                return device.get(CONF_LOCAL_KEY)
        return None


async def async_get_cache(hass: HomeAssistant) -> CloudCache:
    """Get the shared cloud cache, loading it on first use."""
    domain_data = hass.data.setdefault(DOMAIN, {})
    cache = domain_data.get(DATA_CLOUD_CACHE)
    if cache is None:
        cache = CloudCache(hass)
        await cache.async_load()
        domain_data[DATA_CLOUD_CACHE] = cache
    return cache
